### ISSUE TITLE
Sign In - Default Values for mail/password not taken into account

### ISSUE THREAD

**Issue by app-generator** [app-generator/react-horizon-ui-chakra#1]
The default value for the sign in, not taken into account. File:

[src/views/auth/signIn/index.jsx](https://github.com/app-generator/react-horizon-ui-chakra/blob/main/src/views/auth/signIn/index.jsx)

```javascript
  const [email, setEmail] = useState("test@appseed.us");  // default values not working
  const [password, setPassword] = useState("pass");         // default values not working
```

When the default values are set, the values should be automatically injected in to the form and users can authenticate using the default values.

![image](https://user-images.githubusercontent.com/51070104/166092048-c5dfae65-d433-42bd-9f60-e517b47e70d8.png)

**Comment by dadabapa6** [comment]
Done

**Comment by app-generator** [comment]
Fixed.
