### ISSUE TITLE
How can i do the thing like PRO Version?

### ISSUE THREAD

**Issue by Ryan0204** [app-generator/react-horizon-ui-chakra#4]
Hello, i wanna make sub page like pro (Image below)
<img width="713" alt="image" src="https://user-images.githubusercontent.com/82715592/192134855-e876b275-c441-4b56-a670-42f0592a8766.png">

<img width="784" alt="image" src="https://user-images.githubusercontent.com/82715592/192134866-d70815d9-e3d9-4b11-985a-166a519986c5.png">

How can i do it?

**Comment by simmmpleweb** [comment]
Hello, @Ryan0204 ! The accordion with sub paths is a PRO feature. If you want the feature, feel free to upgrade to the PRO version! Regards, Vlad.
