### ISSUE TITLE
issue with routes.js

### ISSUE THREAD

**Issue by itforce2015** [app-generator/react-horizon-ui-chakra#5]
I want the sign in and sign up link not showing in the navbar, but when i delete the link in routes.js, then it works and doesn't show up, but when i log out the try to log in again then i get blank page, i think something messed up with the routes when i deleted this: "  {
    name: 'Sign Up',
    layout: '/auth',
    path: '/sign-up',
    icon: <Icon as={MdLock} width="20px" height="20px" color="inherit" />,
    component: SignUpCentered,
  },"  
  
  
![image](https://github.com/app-generator/react-horizon-ui-chakra/assets/72609957/947476fe-755c-41c4-9719-08b62684e1be)

**Comment by app-generator** [comment]
Hello @rasel-helios 

Also, please remove the `SignIN` and `SignUP` links from the sidebar. 
The users are already authenticated and the links are not useful. 

Ty for your work.

**Comment by app-generator** [comment]
Hello! 

Sorry for the delay. The new AppSeed Service now manages the project and related issues:

https://app-generator.dev/ - Open-Source Platform.

Ty!
