### ISSUE TITLE
Build missing the css and js, while dev works fine

### ISSUE THREAD

**Issue by aaminahassan** [app-generator/react-horizon-ui-chakra#7]
I am deploying the app , and while I do that the built is missing the css and js files . The develop works fine. I changed the home  to 
npx serve did not work. Screen Shot attached. 

```
 "homepage": "./",
  "name": "horizon-ui-chakra",
```

in pakage.json 

[
![Screenshot from 2023-12-28 15-09-08](https://github.com/app-generator/react-horizon-ui-chakra/assets/6203342/0f43a435-e90b-4ff6-921a-a3f665c322bb)
](url)
GET https://10.0.2.15:3000/horizon-ui-chakra/static/js/main.c54503c5.js net::ERR_ABORTED 404 (Not Found)

**Comment by simmmpleweb** [comment]
Hello, @aaminahassan ! The homepage is supposed to be the domain of your website. If you just want to check the build out, delete it entirely! If yo need more assistance, ping me again !
Regards, Vlad.

**Comment by app-generator** [comment]
Hello! 

Sorry for the delay. The new AppSeed Service now manages the project and related issues:

https://app-generator.dev/ - Open-Source Platform.

Ty!
