### ISSUE TITLE
Manual reload require after api hit

### ISSUE THREAD

**Issue by TAYYABA-MUZAFFAR-IQBAL** [app-generator/react-horizon-ui-chakra#8]
I am facing the issue of latest components state did'nt reflect until i reload my page manually and same even after login and logout i am navigating the route but the route on url params changes but no component rendered until i manually reload the page.

**Comment by simmmpleweb** [comment]
Hello, @TAYYABA-MUZAFFAR-IQBAL ! This product does not have any login/logut functionalities implemented, so I cannot really help you, unless you give me more details about the issue. 
Regards, Vlad.

**Comment by app-generator** [comment]
Hello! 

Sorry for the delay. The new AppSeed Service now manages the project and related issues:

https://app-generator.dev/ - Open-Source Platform.

Ty!
